# Generated by Django 5.2.17 on 2026-08-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=40, unique=True)),
                ('unit_model', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='forming', max_length=16)),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_installments', models.PositiveIntegerField()),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('semimonthly', 'Semi-monthly'), ('monthly', 'Monthly')], default='monthly', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['client', 'sequence_no'],
            },
        ),
    ]
