# Generated by Django 5.2.17 on 2026-08-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches_app', '0001_initial'),
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='clients_app.client'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together={('client', 'sequence_no')},
        ),
    ]
