# Generated by Django 5.2.17 on 2026-08-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_customeraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factual_evidence', models.TextField(blank=True)),
                ('evaluation', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, max_length=200)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('noted', 'Noted'), ('action_recommended', 'Action recommended')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_reviews', to='auth_app.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
