# Generated by Django 5.2.17 on 2026-08-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpi_app', '0001_initial'),
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpireview',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_reviews', to='tasks_app.task'),
        ),
    ]
