# Generated by Django 5.2.17 on 2026-08-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_customeraccount'),
        ('clients_app', '0002_client_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('waiting_for_client', 'Waiting for client'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='auth_app.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_cases', to='clients_app.client')),
            ],
            options={
                'ordering': ['-date_received'],
                'indexes': [models.Index(fields=['status'], name='support_app_status_ad6529_idx'), models.Index(fields=['client', 'status'], name='support_app_client__5a9cd6_idx')],
            },
        ),
    ]
