# Generated by Django 5.2.17 on 2026-08-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('batches_app', '0001_initial'),
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(max_length=40)),
                ('reference_no', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs clarification')], default='pending', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='batches_app.batch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients_app.client')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to='auth_app.employee')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches_app.scheduleitem')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_verified', to='auth_app.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'status'], name='payments_ap_client__64cf03_idx'), models.Index(fields=['batch', 'status'], name='payments_ap_batch_i_e4f730_idx'), models.Index(fields=['status'], name='payments_ap_status_7e20a5_idx'), models.Index(fields=['payment_date'], name='payments_ap_payment_68db9d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
    ]
