# Generated by Django 5.2.17 on 2026-08-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0001_initial'),
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage_app.storedfile'),
        ),
    ]
