# Generated by Django 5.2.17 on 2026-08-15 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('coo', 'COO'), ('general_manager', 'General Manager'), ('hr_payroll', 'HR / Payroll'), ('finance_officer', 'Finance Officer'), ('records_monitoring', 'Records & Monitoring'), ('analytics', 'Analytics'), ('cs_head', 'Customer Service Head'), ('cs_team', 'Customer Service Team'), ('core_handler', 'Core Team / Handler')], max_length=24)),
                ('status', models.CharField(default='active', max_length=12)),
                ('hr_confidential_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
