# Generated by Django 5.2.17 on 2026-08-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_customeraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('done', 'Done')], default='todo', max_length=16)),
                ('submission_timestamp', models.DateTimeField(blank=True, null=True)),
                ('late_flag', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='auth_app.employee')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='auth_app.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignee', 'status'], name='tasks_app_t_assigne_64b0ba_idx'), models.Index(fields=['status'], name='tasks_app_t_status_f79964_idx')],
            },
        ),
    ]
